"""update refresh token model

Revision ID: 82c0bb82996d
Revises: 640992f3d894
Create Date: 2026-04-16 11:27:12.674944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c0bb82996d'
down_revision: Union[str, Sequence[str], None] = '640992f3d894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'created_at')
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
